"""Static source templates for the pure Manim emitter."""

from __future__ import annotations

SOURCE_HEADER = """# Generated by VIROC. Do not edit by hand.
from __future__ import annotations

from manim import (
    Arrow,
    Create,
    FadeIn,
    FadeOut,
    Indicate,
    Rectangle,
    Scene,
    Text,
    config,
    linear,
    smooth,
)

"""

STYLE_BLOCK = """_BACKGROUND = "#0B1020"
_STYLES = {
    "edge.default": {"color": "#94A3B8"},
    "edge.lookup": {"color": "#38BDF8"},
    "edge.split": {"color": "#38BDF8"},
    "edge.store": {"color": "#22C55E"},
    "edge.transform": {"color": "#A78BFA"},
    "label": {"color": "#E5E7EB"},
    "node.data_source": {"fill_color": "#1D4ED8", "stroke_color": "#60A5FA"},
    "node.intermediate": {"fill_color": "#7C3AED", "stroke_color": "#C4B5FD"},
    "node.model": {"fill_color": "#BE123C", "stroke_color": "#FDA4AF"},
    "node.process": {"fill_color": "#0891B2", "stroke_color": "#67E8F9"},
    "node.storage": {"fill_color": "#047857", "stroke_color": "#6EE7B7"},
}


def _style(ref: str) -> dict[str, str]:
    return _STYLES.get(ref, {"color": "#E5E7EB"})


def _rate_func(name: str):
    if name == "linear":
        return linear
    return smooth

"""

GEOMETRY_HELPERS = """def _x(value: float) -> float:
    return (value / config.pixel_width) * config.frame_width - (config.frame_width / 2)


def _y(value: float) -> float:
    return (config.frame_height / 2) - (value / config.pixel_height) * config.frame_height


def _width(value: float) -> float:
    return (value / config.pixel_width) * config.frame_width


def _height(value: float) -> float:
    return (value / config.pixel_height) * config.frame_height


def _center(x: float, y: float, w: float, h: float) -> tuple[float, float, float]:
    return (_x(x + w / 2), _y(y + h / 2), 0.0)


def _rect(x: float, y: float, w: float, h: float, style_ref: str) -> Rectangle:
    style = _style(style_ref)
    return Rectangle(
        width=_width(w),
        height=_height(h),
        fill_opacity=0.75,
        stroke_width=2,
        **style,
    ).move_to(_center(x, y, w, h))


def _text(text: str, x: float, y: float, w: float, h: float, style_ref: str) -> Text:
    style = _style(style_ref)
    return Text(text, font_size=32, **style).scale_to_fit_width(_width(w)).move_to(
        _center(x, y, w, h)
    )


def _arrow(x: float, y: float, w: float, h: float, style_ref: str) -> Arrow:
    style = _style(style_ref)
    return Arrow(
        start=(_x(x), _y(y + h / 2), 0.0),
        end=(_x(x + w), _y(y + h / 2), 0.0),
        buff=0,
        stroke_width=max(_height(h), 2),
        **style,
    )

"""

__all__ = ["GEOMETRY_HELPERS", "SOURCE_HEADER", "STYLE_BLOCK"]
