"""Static source templates for the pure Manim emitter.

The emitter resolves each object's :mod:`viroc.adapters._palette` colors at emit
time and bakes literal hex into the ``_rect``/``_text``/``_arrow`` calls, so the
generated ``scene.py`` is self-contained and byte-deterministic and these
helpers never look styles up at render time.
"""

from __future__ import annotations

SOURCE_HEADER = """# Generated by VIROC. Do not edit by hand.
# ruff: noqa: E501
# pyright: reportMissingImports=false
# pyright: reportUnknownVariableType=false
# pyright: reportUnknownMemberType=false
# pyright: reportUnknownParameterType=false
# pyright: reportUnknownArgumentType=false
# pyright: reportArgumentType=false
# pyright: reportAttributeAccessIssue=false
# pyright: reportCallIssue=false
# pyright: reportUntypedBaseClass=false
from manim import (
    BOLD,
    Arrow,
    Create,
    FadeIn,
    FadeOut,
    Indicate,
    RoundedRectangle,
    Scene,
    Text,
    config,
    linear,
    smooth,
)

"""

HELPERS = """_BACKGROUND = "#0B1020"
_FONT = "Helvetica"
_FONT_SIZE = 34
_CAPTION_SIZE = 30
_CAPTION_COLOR = "#E2E8F0"


def _x(value: float) -> float:
    return (value / config.pixel_width) * config.frame_width - (config.frame_width / 2)


def _y(value: float) -> float:
    return (config.frame_height / 2) - (value / config.pixel_height) * config.frame_height


def _width(value: float) -> float:
    return (value / config.pixel_width) * config.frame_width


def _height(value: float) -> float:
    return (value / config.pixel_height) * config.frame_height


def _center(x: float, y: float, w: float, h: float) -> tuple[float, float, float]:
    return (_x(x + w / 2), _y(y + h / 2), 0.0)


def _rate_func(name: str):
    if name == "linear":
        return linear
    return smooth


def _rect(x: float, y: float, w: float, h: float, fill: str, stroke: str) -> RoundedRectangle:
    return RoundedRectangle(
        width=_width(w),
        height=_height(h),
        corner_radius=min(_width(w), _height(h)) * 0.14,
        fill_color=fill,
        fill_opacity=0.92,
        stroke_color=stroke,
        stroke_width=3,
    ).move_to(_center(x, y, w, h))


def _text(text: str, x: float, y: float, w: float, h: float, color: str) -> Text:
    label = Text(text, font=_FONT, font_size=_FONT_SIZE, color=color, weight=BOLD)
    max_w = _width(w) * 0.86
    max_h = _height(h) * 0.72
    if label.width > max_w:
        label.scale_to_fit_width(max_w)
    if label.height > max_h:
        label.scale_to_fit_height(max_h)
    return label.move_to(_center(x, y, w, h))


def _arrow(x: float, y: float, w: float, h: float, color: str) -> Arrow:
    return Arrow(
        start=(_x(x), _y(y + h / 2), 0.0),
        end=(_x(x + w), _y(y + h / 2), 0.0),
        buff=0,
        stroke_width=6,
        color=color,
        max_tip_length_to_length_ratio=0.2,
    )


def _caption(text: str) -> Text:
    line = Text(text, font=_FONT, font_size=_CAPTION_SIZE, color=_CAPTION_COLOR)
    max_w = config.frame_width * 0.86
    if line.width > max_w:
        line.scale_to_fit_width(max_w)
    line.move_to((0.0, -config.frame_height / 2 + line.height / 2 + 0.4, 0.0))
    return line

"""

__all__ = ["HELPERS", "SOURCE_HEADER"]
