"""Static templates and defaults for the Remotion source emitter."""

from __future__ import annotations

SOURCE_HEADER = "/* Generated by VIROC. Do not edit by hand. */\n"

PACKAGE_JSON_TEMPLATE: dict[str, object] = {
    "name": "viroc-remotion-scene",
    "private": True,
    "type": "module",
    "scripts": {
        "render": "remotion render src/index.ts VirocScene out/viroc.mp4",
    },
    "dependencies": {
        "react": "^19.0.0",
        "react-dom": "^19.0.0",
        "remotion": "^4.0.0",
    },
    "devDependencies": {
        "@types/node": "^22.0.0",
        "@types/react": "^19.0.0",
        "typescript": "^5.0.0",
    },
}

TSCONFIG_JSON_TEMPLATE: dict[str, object] = {
    "compilerOptions": {
        "target": "ES2022",
        "module": "ESNext",
        "moduleResolution": "Bundler",
        "jsx": "react-jsx",
        "strict": True,
        "esModuleInterop": True,
        "skipLibCheck": True,
        "noEmit": True,
        "types": ["node"],
    },
    "include": ["src"],
}

INDEX_TS = """import {registerRoot} from \"remotion\";
import {RemotionRoot} from \"./Root\";

registerRoot(RemotionRoot);
"""

__all__ = [
    "INDEX_TS",
    "PACKAGE_JSON_TEMPLATE",
    "SOURCE_HEADER",
    "TSCONFIG_JSON_TEMPLATE",
]
