"""Static templates and defaults for the Remotion source emitter."""

from __future__ import annotations

SOURCE_HEADER = "/* Generated by VIROC. Do not edit by hand. */\n"

PACKAGE_JSON_TEMPLATE: dict[str, object] = {
    "name": "viroc-remotion-scene",
    "private": True,
    "type": "module",
    "scripts": {
        "render": "remotion render src/index.ts VirocScene out/viroc.mp4",
    },
    "dependencies": {
        "react": "^19.0.0",
        "react-dom": "^19.0.0",
        "remotion": "^4.0.0",
    },
    "devDependencies": {
        "@types/node": "^22.0.0",
        "@types/react": "^19.0.0",
        "typescript": "^5.0.0",
    },
}

TSCONFIG_JSON_TEMPLATE: dict[str, object] = {
    "compilerOptions": {
        "target": "ES2022",
        "module": "ESNext",
        "moduleResolution": "Bundler",
        "jsx": "react-jsx",
        "strict": True,
        "esModuleInterop": True,
        "skipLibCheck": True,
        "noEmit": True,
        "types": ["node"],
    },
    "include": ["src"],
}

INDEX_TS = """import {registerRoot} from \"remotion\";
import {RemotionRoot} from \"./Root\";

registerRoot(RemotionRoot);
"""

STYLE_TOKENS: dict[str, dict[str, str]] = {
    "edge.default": {"color": "#94A3B8"},
    "edge.lookup": {"color": "#38BDF8"},
    "edge.split": {"color": "#38BDF8"},
    "edge.store": {"color": "#22C55E"},
    "edge.transform": {"color": "#A78BFA"},
    "label": {"color": "#E5E7EB"},
    "node.data_source": {"fill_color": "#1D4ED8", "stroke_color": "#60A5FA"},
    "node.intermediate": {"fill_color": "#7C3AED", "stroke_color": "#C4B5FD"},
    "node.model": {"fill_color": "#BE123C", "stroke_color": "#FDA4AF"},
    "node.process": {"fill_color": "#0891B2", "stroke_color": "#67E8F9"},
    "node.storage": {"fill_color": "#047857", "stroke_color": "#6EE7B7"},
}

__all__ = [
    "INDEX_TS",
    "PACKAGE_JSON_TEMPLATE",
    "SOURCE_HEADER",
    "STYLE_TOKENS",
    "TSCONFIG_JSON_TEMPLATE",
]
