"""Static templates and defaults for the Motion Canvas source emitter."""

from __future__ import annotations

SOURCE_HEADER = "/* Generated by VIROC. Do not edit by hand. */\n"

PACKAGE_JSON_TEMPLATE: dict[str, object] = {
    "name": "viroc-motion-canvas-scene",
    "private": True,
    "type": "module",
    "scripts": {
        "dev": "vite",
        "build": "tsc && vite build",
    },
    "dependencies": {
        "@motion-canvas/2d": "^3.17.2",
        "@motion-canvas/core": "^3.17.2",
    },
    "devDependencies": {
        "@motion-canvas/ffmpeg": "^3.17.2",
        "@motion-canvas/ui": "^3.17.2",
        "@motion-canvas/vite-plugin": "^3.17.2",
        "typescript": "^5.2.2",
        "vite": "^5.4.0",
    },
}

TSCONFIG_JSON_TEMPLATE: dict[str, object] = {
    "extends": "@motion-canvas/2d/tsconfig.project.json",
    "include": ["src"],
}

VITE_CONFIG_TS = """import {defineConfig} from \"vite\";
import motionCanvas from \"@motion-canvas/vite-plugin\";
import ffmpeg from \"@motion-canvas/ffmpeg\";

export default defineConfig({
  plugins: [motionCanvas(), ffmpeg()],
});
"""

MOTION_CANVAS_D_TS = '/// <reference types="@motion-canvas/core/project" />\n'

STYLE_TOKENS: dict[str, dict[str, str]] = {
    "edge.default": {"color": "#94A3B8"},
    "edge.lookup": {"color": "#38BDF8"},
    "edge.split": {"color": "#38BDF8"},
    "edge.store": {"color": "#22C55E"},
    "edge.transform": {"color": "#A78BFA"},
    "label": {"color": "#E5E7EB"},
    "node.data_source": {"fill_color": "#1D4ED8", "stroke_color": "#60A5FA"},
    "node.intermediate": {"fill_color": "#7C3AED", "stroke_color": "#C4B5FD"},
    "node.model": {"fill_color": "#BE123C", "stroke_color": "#FDA4AF"},
    "node.process": {"fill_color": "#0891B2", "stroke_color": "#67E8F9"},
    "node.storage": {"fill_color": "#047857", "stroke_color": "#6EE7B7"},
}

__all__ = [
    "MOTION_CANVAS_D_TS",
    "PACKAGE_JSON_TEMPLATE",
    "SOURCE_HEADER",
    "STYLE_TOKENS",
    "TSCONFIG_JSON_TEMPLATE",
    "VITE_CONFIG_TS",
]
