"""Static templates for the pure HTML emitter."""

from __future__ import annotations

SOURCE_HEADER = """<!doctype html>
<!-- Generated by VIROC. Do not edit by hand. -->
<html lang=\"en\">
<head>
<meta charset=\"utf-8\" />
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
<title>VIROC Scene</title>
"""

STYLE_TOKENS: dict[str, dict[str, str]] = {
    "edge.default": {"color": "#94A3B8"},
    "edge.lookup": {"color": "#38BDF8"},
    "edge.split": {"color": "#38BDF8"},
    "edge.store": {"color": "#22C55E"},
    "edge.transform": {"color": "#A78BFA"},
    "label": {"color": "#E5E7EB"},
    "node.data_source": {"fill_color": "#1D4ED8", "stroke_color": "#60A5FA"},
    "node.intermediate": {"fill_color": "#7C3AED", "stroke_color": "#C4B5FD"},
    "node.model": {"fill_color": "#BE123C", "stroke_color": "#FDA4AF"},
    "node.process": {"fill_color": "#0891B2", "stroke_color": "#67E8F9"},
    "node.storage": {"fill_color": "#047857", "stroke_color": "#6EE7B7"},
}

BASE_CSS = """<style>
:root {
  color-scheme: dark;
  --background: #0B1020;
  --foreground: #E5E7EB;
  --highlight: #FBBF24;
  --shadow: rgba(11, 16, 32, 0.45);
}
* { box-sizing: border-box; }
html, body {
  margin: 0;
  background: var(--background);
  color: var(--foreground);
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}
body {
  min-height: 100vh;
  display: grid;
  place-items: center;
}
#scene {
  position: relative;
  overflow: hidden;
  background:
    radial-gradient(circle at 20% 20%, rgba(56, 189, 248, 0.08), transparent 30%),
    radial-gradient(circle at 80% 10%, rgba(167, 139, 250, 0.08), transparent 30%),
    linear-gradient(180deg, rgba(15, 23, 42, 0.96), rgba(11, 16, 32, 1));
  box-shadow: 0 24px 64px rgba(0, 0, 0, 0.35);
  isolation: isolate;
}
.layer {
  position: absolute;
  inset: 0;
  pointer-events: none;
}
.object {
  position: absolute;
  opacity: 0;
  transform-origin: center center;
  will-change: opacity, transform, filter;
}
.object[data-visible=\"true\"] { opacity: 1; }
.object.is-highlighted {
  filter: drop-shadow(0 0 18px rgba(251, 191, 36, 0.4));
}
.primitive-rect {
  border-radius: 18px;
  border: 2px solid var(--stroke-color, var(--foreground));
  background: linear-gradient(180deg, color-mix(in srgb, var(--fill-color, #1D4ED8) 82%, white 18%), var(--fill-color, #1D4ED8));
  box-shadow: 0 10px 28px var(--shadow);
}
.primitive-text,
.primitive-code,
.primitive-formula,
.primitive-icon {
  display: grid;
  place-items: center;
  text-align: center;
  color: var(--color, var(--foreground));
}
.primitive-text > span {
  font-size: 32px;
  font-weight: 600;
  letter-spacing: -0.02em;
  line-height: 1.1;
}
.primitive-code > pre {
  margin: 0;
  width: 100%;
  height: 100%;
  display: grid;
  place-items: center;
  padding: 14px 18px;
  border-radius: 14px;
  background: rgba(15, 23, 42, 0.78);
  border: 1px solid rgba(148, 163, 184, 0.28);
  font: 600 20px/1.3 ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  box-shadow: 0 10px 28px var(--shadow);
}
.primitive-formula > div {
  width: 100%;
  height: 100%;
  display: grid;
  place-items: center;
  border-radius: 16px;
  background: rgba(15, 23, 42, 0.42);
  border: 1px solid rgba(229, 231, 235, 0.24);
  font: italic 600 26px/1.2 "Times New Roman", Georgia, serif;
}
.primitive-icon > div {
  width: 100%;
  height: 100%;
  display: grid;
  place-items: center;
  border-radius: 999px;
  background: radial-gradient(circle at 30% 30%, rgba(255, 255, 255, 0.2), transparent 35%), var(--fill-color, #0891B2);
  border: 2px solid var(--stroke-color, rgba(229, 231, 235, 0.4));
  box-shadow: 0 10px 28px var(--shadow);
  font-size: 34px;
  font-weight: 700;
}
.primitive-arrow svg {
  display: block;
  width: 100%;
  height: 100%;
  overflow: visible;
}
.primitive-arrow line,
.primitive-arrow path {
  stroke: var(--color, var(--foreground));
  fill: var(--color, var(--foreground));
  stroke-linecap: round;
  stroke-linejoin: round;
}
.caption {
  position: absolute;
  left: 96px;
  right: 96px;
  bottom: 48px;
  min-height: 72px;
  display: grid;
  align-items: center;
  justify-items: center;
  padding: 14px 18px;
  border-radius: 18px;
  background: rgba(11, 16, 32, 0.72);
  border: 1px solid rgba(229, 231, 235, 0.14);
  color: var(--foreground);
  font-size: 28px;
  font-weight: 500;
  line-height: 1.25;
  letter-spacing: -0.01em;
  text-align: center;
  opacity: 0;
}
.caption[data-visible=\"true\"] { opacity: 1; }
</style>
"""

RUNTIME_SCRIPT = """<script>
const DATA = __VIROC_DATA__;
const scene = document.getElementById("scene");
const captionNode = document.getElementById("caption");
const nodes = new Map();
for (const element of document.querySelectorAll("[data-object-id]")) {
  nodes.set(element.dataset.objectId, element);
}
const animationsByObject = new Map();
for (const keyframe of DATA.keyframes) {
  const list = animationsByObject.get(keyframe.object_id) ?? [];
  list.push(keyframe);
  animationsByObject.set(keyframe.object_id, list);
}
for (const entries of animationsByObject.values()) {
  entries.sort((a, b) => a.start_f - b.start_f || a.end_f - b.end_f || a.kind.localeCompare(b.kind));
}
function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}
function ease(name, value) {
  const t = clamp(value, 0, 1);
  if (name === "linear") return t;
  if (name === "spring") {
    return 1 - Math.cos(t * Math.PI * 4) * Math.exp(-6 * t);
  }
  return t * t * (3 - 2 * t);
}
function drawProgress(element, progress) {
  const line = element.querySelector("line");
  const head = element.querySelector("path");
  if (!line || !head) return;
  const length = Number(element.dataset.length || "0");
  const clamped = clamp(progress, 0, 1);
  line.style.strokeDasharray = String(length);
  line.style.strokeDashoffset = String(length * (1 - clamped));
  head.style.opacity = clamped <= 0 ? "0" : "1";
}
function setCaption(frame) {
  let active = "";
  for (const caption of DATA.captions) {
    if (frame >= caption.start_f && frame < caption.end_f) {
      active = caption.text;
      break;
    }
  }
  captionNode.textContent = active;
  captionNode.dataset.visible = active ? "true" : "false";
}
function applyFrame(frameValue) {
  const frame = Math.max(0, Math.trunc(frameValue));
  scene.dataset.frame = String(frame);
  for (const object of DATA.objects) {
    const element = nodes.get(object.id);
    if (!element) continue;
    let opacity = 1;
    let scale = 1;
    let highlighted = false;
    let drawn = object.primitive === "arrow" ? 0 : 1;
    const animations = animationsByObject.get(object.id) ?? [];
    if (animations.length > 0) {
      opacity = 0;
      for (const keyframe of animations) {
        const span = Math.max(1, keyframe.end_f - keyframe.start_f);
        if (keyframe.kind === "fade_in") {
          if (frame < keyframe.start_f) continue;
          if (frame >= keyframe.end_f) {
            opacity = 1;
            continue;
          }
          opacity = ease(keyframe.easing, (frame - keyframe.start_f) / span);
        } else if (keyframe.kind === "fade_out") {
          if (frame < keyframe.start_f) continue;
          if (frame >= keyframe.end_f) {
            opacity = 0;
            continue;
          }
          opacity = 1 - ease(keyframe.easing, (frame - keyframe.start_f) / span);
        } else if (keyframe.kind === "draw") {
          if (frame < keyframe.start_f) continue;
          if (frame >= keyframe.end_f) {
            drawn = 1;
            opacity = 1;
            continue;
          }
          drawn = ease(keyframe.easing, (frame - keyframe.start_f) / span);
          opacity = Math.max(opacity, drawn);
        } else if (keyframe.kind === "highlight") {
          if (frame < keyframe.start_f || frame >= keyframe.end_f) continue;
          const pulse = ease(keyframe.easing, (frame - keyframe.start_f) / span);
          highlighted = true;
          scale = 1 + pulse * 0.035;
          opacity = Math.max(opacity, 1);
        }
      }
    }
    element.style.opacity = String(clamp(opacity, 0, 1));
    element.style.transform = `scale(${scale})`;
    element.dataset.visible = opacity > 0 ? "true" : "false";
    element.classList.toggle("is-highlighted", highlighted);
    if (object.primitive === "arrow") {
      drawProgress(element, drawn);
    }
  }
  setCaption(frame);
  return frame;
}
window.__viroc_setFrame = applyFrame;
window.__viroc_frame_count = DATA.total_frames;
const params = new URLSearchParams(window.location.search);
const initialFrame = Number(params.get("frame") ?? "0");
applyFrame(initialFrame);
</script>
"""

__all__ = ["BASE_CSS", "RUNTIME_SCRIPT", "SOURCE_HEADER", "STYLE_TOKENS"]
